import type { LessonPlanPayload, WorksheetPayload, QuizPayload, ExportResults } from '../types';

interface DocBlock {
  text: string;
  paragraphStyle?: 'HEADING_1' | 'HEADING_2' | 'HEADING_3' | 'NORMAL_TEXT' | 'SUBTITLE';
  bold?: boolean;
  bullet?: boolean;
}

/**
 * Ensures or creates the "AI Lesson Planner" root folder in Google Drive
 */
export async function getOrCreateLessonPlannerFolder(accessToken: string): Promise<{ id: string; url: string }> {
  const query = encodeURIComponent("name = 'AI Lesson Planner' and mimeType = 'application/vnd.google-apps.folder' and trashed = false");
  const searchRes = await fetch(`https://www.googleapis.com/drive/v3/files?q=${query}&fields=files(id,name,webViewLink)`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!searchRes.ok) {
    const errText = await searchRes.text();
    console.warn('Drive folder lookup returned non-200:', errText);
  } else {
    const data = await searchRes.json();
    if (data.files && data.files.length > 0) {
      return {
        id: data.files[0].id,
        url: data.files[0].webViewLink || `https://drive.google.com/drive/folders/${data.files[0].id}`,
      };
    }
  }

  // Create folder
  const createRes = await fetch('https://www.googleapis.com/drive/v3/files', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: 'AI Lesson Planner',
      mimeType: 'application/vnd.google-apps.folder',
      description: 'End-to-end curriculum materials generated by AI Lesson Planner',
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json().catch(() => ({}));
    throw new Error(`Failed to create Drive folder: ${err.error?.message || createRes.statusText}`);
  }

  const folderData = await createRes.json();
  return {
    id: folderData.id,
    url: folderData.webViewLink || `https://drive.google.com/drive/folders/${folderData.id}`,
  };
}

/**
 * Moves an item into the specified folder in Google Drive
 */
export async function moveFileToFolder(fileId: string, folderId: string, accessToken: string): Promise<void> {
  try {
    const res = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}?addParents=${folderId}&fields=id,parents`, {
      method: 'PATCH',
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    if (!res.ok) {
      console.warn(`Could not add parent folder for file ${fileId}:`, await res.text());
    }
  } catch (e) {
    console.warn(`moveFileToFolder error for ${fileId}:`, e);
  }
}

/**
 * Creates and formats a Google Doc with structured headings, bold titles, and bullet lists
 */
async function createStyledGoogleDoc(
  title: string,
  blocks: DocBlock[],
  accessToken: string
): Promise<{ docId: string; docUrl: string }> {
  // Step 1: Create empty document
  const createRes = await fetch('https://docs.googleapis.com/v1/documents', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ title }),
  });

  if (!createRes.ok) {
    const err = await createRes.json().catch(() => ({}));
    throw new Error(`Failed to create Google Doc "${title}": ${err.error?.message || createRes.statusText}`);
  }

  const docData = await createRes.json();
  const docId = docData.documentId;
  const docUrl = `https://docs.google.com/document/d/${docId}/edit`;

  // Step 2: Build cumulative text & record ranges
  let accumulatedText = '';
  interface StyleRange {
    startIndex: number;
    endIndex: number;
    paragraphStyle?: string;
    bold?: boolean;
    bullet?: boolean;
  }
  const ranges: StyleRange[] = [];

  for (const block of blocks) {
    const textToAdd = block.text.endsWith('\n') ? block.text : block.text + '\n';
    const startIndex = accumulatedText.length + 1; // Google Docs index starts at 1
    accumulatedText += textToAdd;
    const endIndex = accumulatedText.length + 1;

    ranges.push({
      startIndex,
      endIndex,
      paragraphStyle: block.paragraphStyle,
      bold: block.bold,
      bullet: block.bullet,
    });
  }

  // Step 3: Send batchUpdate requests
  const requests: any[] = [];

  // Insert full text
  requests.push({
    insertText: {
      location: { index: 1 },
      text: accumulatedText,
    },
  });

  // Apply styles
  for (const r of ranges) {
    if (r.paragraphStyle) {
      requests.push({
        updateParagraphStyle: {
          range: {
            startIndex: r.startIndex,
            endIndex: r.endIndex,
          },
          paragraphStyle: {
            namedStyleType: r.paragraphStyle,
          },
          fields: 'namedStyleType',
        },
      });
    }

    if (r.bold) {
      requests.push({
        updateTextStyle: {
          range: {
            startIndex: r.startIndex,
            endIndex: r.endIndex,
          },
          textStyle: {
            bold: true,
          },
          fields: 'bold',
        },
      });
    }

    if (r.bullet) {
      requests.push({
        createParagraphBullets: {
          range: {
            startIndex: r.startIndex,
            endIndex: r.endIndex,
          },
          bulletPreset: 'BULLET_DISC_CIRCLE_SQUARE',
        },
      });
    }
  }

  const updateRes = await fetch(`https://docs.googleapis.com/v1/documents/${docId}:batchUpdate`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ requests }),
  });

  if (!updateRes.ok) {
    console.warn(`Doc batchUpdate encountered a warning:`, await updateRes.text());
  }

  return { docId, docUrl };
}

/**
 * Generates the Lesson Plan Google Doc blocks
 */
export function buildLessonPlanBlocks(plan: LessonPlanPayload): DocBlock[] {
  const blocks: DocBlock[] = [];

  // Title & Metadata
  blocks.push({ text: plan.title, paragraphStyle: 'HEADING_1', bold: true });
  blocks.push({
    text: `Grade Level: ${plan.gradeLevel}   |   Instructional Duration: ${plan.durationMinutes} Minutes\nCurriculum Standard: ${plan.standardsOverview}\n`,
    paragraphStyle: 'SUBTITLE',
  });

  // Learning Objectives
  blocks.push({ text: '1. Learning Objectives', paragraphStyle: 'HEADING_2', bold: true });
  for (const obj of plan.objectives) {
    blocks.push({ text: obj, paragraphStyle: 'NORMAL_TEXT', bullet: true });
  }
  blocks.push({ text: '' }); // Spacing

  // Materials Required
  blocks.push({ text: '2. Required Materials & Tech Prep', paragraphStyle: 'HEADING_2', bold: true });
  for (const mat of plan.materials) {
    blocks.push({ text: mat, paragraphStyle: 'NORMAL_TEXT', bullet: true });
  }
  blocks.push({ text: '' }); // Spacing

  // Timed Agenda & Pedagogical Flow
  blocks.push({ text: '3. Timed Instructional Agenda', paragraphStyle: 'HEADING_2', bold: true });
  for (const item of plan.agenda) {
    blocks.push({
      text: `• [${item.minutes} min] ${item.segment}`,
      bold: true,
      paragraphStyle: 'NORMAL_TEXT',
    });
    blocks.push({
      text: `   ${item.instructions}\n`,
      paragraphStyle: 'NORMAL_TEXT',
    });
  }

  // Teacher Notes / Differentiation
  blocks.push({ text: '4. Formative Assessment & Checkpoints', paragraphStyle: 'HEADING_2', bold: true });
  blocks.push({
    text: '• Gauge student mastery through the accompanying student practice worksheet.\n• Administer the synchronized 5-question Google Forms exit ticket in the final 5 minutes of class.\n• Review instant auto-graded responses to inform small-group interventions.',
    paragraphStyle: 'NORMAL_TEXT',
  });

  return blocks;
}

/**
 * Generates the Printable Student Worksheet Google Doc blocks
 */
export function buildWorksheetBlocks(ws: WorksheetPayload): DocBlock[] {
  const blocks: DocBlock[] = [];

  // Header for student info
  blocks.push({ text: ws.title, paragraphStyle: 'HEADING_1', bold: true });
  blocks.push({
    text: `Student Name: _______________________      Date: ______________      Period: _____      Score: ____ / 10\n`,
    paragraphStyle: 'NORMAL_TEXT',
    bold: true,
  });

  // Instructions
  blocks.push({ text: 'Instructions', paragraphStyle: 'HEADING_2', bold: true });
  blocks.push({
    text: ws.instructions || 'Carefully review key concepts and answer each practice exercise thoroughly.',
    paragraphStyle: 'NORMAL_TEXT',
  });
  blocks.push({ text: '' });

  // Key Vocabulary Bank
  if (ws.vocabulary && ws.vocabulary.length > 0) {
    blocks.push({ text: 'Key Concept Vocabulary Bank', paragraphStyle: 'HEADING_2', bold: true });
    for (const vocab of ws.vocabulary) {
      blocks.push({
        text: `${vocab.term}: ${vocab.definition}`,
        paragraphStyle: 'NORMAL_TEXT',
        bullet: true,
      });
    }
    blocks.push({ text: '' });
  }

  // Practice Exercises with answer lines
  blocks.push({ text: 'Practice Exercises', paragraphStyle: 'HEADING_2', bold: true });
  for (const ex of ws.exercises) {
    blocks.push({
      text: `Question ${ex.questionNumber}: ${ex.prompt}`,
      bold: true,
      paragraphStyle: 'NORMAL_TEXT',
    });

    // Provide clean blank answer lines
    const lineCount = Math.max(2, Math.min(ex.answerLines || 3, 5));
    const linesStr = Array.from({ length: lineCount }, () => '_________________________________________________________________________________').join('\n');
    blocks.push({
      text: linesStr + '\n',
      paragraphStyle: 'NORMAL_TEXT',
    });
  }

  // Teacher Answer Key Section (Page Break notation)
  blocks.push({ text: '--------------------------------------------------', paragraphStyle: 'NORMAL_TEXT' });
  blocks.push({ text: 'TEACHER ANSWER KEY (Detachable)', paragraphStyle: 'HEADING_3', bold: true });
  for (const ex of ws.exercises) {
    blocks.push({
      text: `Q${ex.questionNumber} Key: ${ex.sampleAnswer || 'Refer to lesson discussion and standard criteria.'}`,
      paragraphStyle: 'NORMAL_TEXT',
    });
  }

  return blocks;
}

/**
 * Creates a configured self-grading Google Form Quiz
 */
export async function createGoogleFormQuiz(
  quiz: QuizPayload,
  topic: string,
  gradeLevel: string,
  accessToken: string
): Promise<{ formId: string; editUrl: string; publicUrl: string }> {
  const formTitle = `[Quiz] ${topic} - ${gradeLevel}`;

  // Step 1: Create empty form
  const createRes = await fetch('https://forms.googleapis.com/v1/forms', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      info: {
        title: formTitle,
        documentTitle: formTitle,
      },
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json().catch(() => ({}));
    throw new Error(`Failed to create Google Form: ${err.error?.message || createRes.statusText}`);
  }

  const formData = await createRes.json();
  const formId = formData.formId;
  const editUrl = `https://docs.google.com/forms/d/${formId}/edit`;
  const publicUrl = formData.responderUri || `https://docs.google.com/forms/d/e/${formId}/viewform`;

  // Step 2: BatchUpdate to make it a self-grading quiz and insert 5 questions
  const requests: any[] = [];

  // Enable quiz mode
  requests.push({
    updateSettings: {
      settings: {
        quizSettings: {
          isQuiz: true,
        },
      },
      updateMask: 'quizSettings.isQuiz',
    },
  });

  // Insert 5 Multiple Choice Questions
  quiz.questions.forEach((q, index) => {
    const correctOptionText = q.options[q.correctIndex] || q.options[0];
    requests.push({
      createItem: {
        item: {
          title: `${index + 1}. ${q.prompt}`,
          description: 'Select the best answer.',
          questionItem: {
            question: {
              required: true,
              grading: {
                pointValue: 1,
                correctAnswers: {
                  answers: [{ value: correctOptionText }],
                },
                whenRight: {
                  text: `Correct! ${q.explanation}`,
                },
                whenWrong: {
                  text: `Review: ${q.explanation}`,
                },
              },
              choiceQuestion: {
                type: 'RADIO',
                options: q.options.map((opt) => ({ value: opt })),
                shuffle: false,
              },
            },
          },
        },
        location: {
          index: index,
        },
      },
    });
  });

  const updateRes = await fetch(`https://forms.googleapis.com/v1/forms/${formId}:batchUpdate`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ requests }),
  });

  if (!updateRes.ok) {
    const errBody = await updateRes.text();
    console.warn('Forms batchUpdate warning:', errBody);
  }

  return { formId, editUrl, publicUrl };
}

/**
 * Complete Workspace Asset Dispatch Pipeline (US-04)
 * Executes simultaneous creation of Lesson Plan Doc, Worksheet Doc, and Form Quiz,
 * places them into the "AI Lesson Planner" Google Drive folder, and returns direct URLs.
 */
export async function exportLessonTriadToWorkspace(
  lessonPlan: LessonPlanPayload,
  worksheet: WorksheetPayload,
  quiz: QuizPayload,
  topic: string,
  gradeLevel: string,
  accessToken: string,
  onProgress?: (statusText: string, step: number) => void
): Promise<ExportResults> {
  onProgress?.('Accessing your "AI Lesson Planner" folder in Google Drive...', 1);
  const folder = await getOrCreateLessonPlannerFolder(accessToken);

  onProgress?.('Generating formatted Lesson Plan Google Doc...', 2);
  const planBlocks = buildLessonPlanBlocks(lessonPlan);
  const planDocTitle = `[Lesson Plan] ${topic} - ${gradeLevel}`;
  const planDocPromise = createStyledGoogleDoc(planDocTitle, planBlocks, accessToken);

  onProgress?.('Generating student-ready Printable Worksheet Doc...', 3);
  const wsBlocks = buildWorksheetBlocks(worksheet);
  const wsDocTitle = `[Worksheet] ${topic} - ${gradeLevel}`;
  const wsDocPromise = createStyledGoogleDoc(wsDocTitle, wsBlocks, accessToken);

  onProgress?.('Building self-grading Google Form Quiz (5 questions, 1 pt each)...', 4);
  const formPromise = createGoogleFormQuiz(quiz, topic, gradeLevel, accessToken);

  // Execute concurrently as per PRD latency benchmark (< 6s concurrent)
  const [planResult, wsResult, formResult] = await Promise.all([
    planDocPromise,
    wsDocPromise,
    formPromise,
  ]);

  onProgress?.('Organizing all materials in your Google Drive folder...', 5);
  // Move all 3 files into the AI Lesson Planner folder in parallel
  await Promise.all([
    moveFileToFolder(planResult.docId, folder.id, accessToken),
    moveFileToFolder(wsResult.docId, folder.id, accessToken),
    moveFileToFolder(formResult.formId, folder.id, accessToken),
  ]);

  onProgress?.('Complete! All assets deployed to Google Workspace.', 6);

  return {
    folderId: folder.id,
    folderUrl: folder.url,
    lessonPlanDocId: planResult.docId,
    lessonPlanDocUrl: planResult.docUrl,
    worksheetDocId: wsResult.docId,
    worksheetDocUrl: wsResult.docUrl,
    quizFormId: formResult.formId,
    quizFormEditUrl: formResult.editUrl,
    quizFormPublicUrl: formResult.publicUrl,
    exportedAt: new Date().toISOString(),
  };
}
